apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app: edgedelta
  labels:
    app: edgedelta
    k8s-apps: edgedelta-logging
    # release needs to match prometheus-operator release name
    # helm ls -n monitoring
    release: prom-kube-stack
  # name should match default servicemonitors
  # kubectl get servicemonitor -n monitoring
  name: promop-prometheus-operator-edgedelta

  namespace: monitoring
spec:
  endpoints:
    - port: metrics
      interval: 15s
  jobLabel: edgedelta
  namespaceSelector:
    matchNames:
    - edgedelta
  selector:
    matchLabels:
      k8s-app: edgedelta-logging
