apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app: edgedelta
  labels:
    app: edgedelta
    k8s-apps: edgedelta-logging
    # release needs to match prometheus-operator release name
    # helm ls -n monitoring
    release: prom-kube-stack
  # name should match default servicemonitors
  # kubectl get servicemonitor -n monitoring
  name: promop-prometheus-operator-edgedelta

  namespace: monitoring
spec:
  endpoints:
    - port: metrics
      interval: 15s
  jobLabel: edgedelta
  namespaceSelector:
    matchNames:
    - edgedelta
  selector:
    matchLabels:
      k8s-app: edgedelta-logging
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: edgedelta
    k8s-app: edgedelta-logging
    jobLabel:  edgedelta
  name: edgedelta-metrics
  namespace: edgedelta
spec:
  ports:
  - name: metrics
    port: 6062
    protocol: TCP
    targetPort: 6062
  selector:
    k8s-app: edgedelta-logging
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
