---
# Source: edgedelta-coordinator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgedelta-coordinator
  namespace: edgedelta
  labels:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
---
# Source: edgedelta-coordinator/templates/claims.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgedelta-coordinator
  namespace: edgedelta
  labels:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Source: edgedelta-coordinator/templates/service_account.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedelta-coordinator
  namespace: edgedelta
  labels:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - pods/log
  - events
  - nodes
  - nodes/metrics
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups: [""] # "" indicates the core API group
  resources:
  - events
  verbs:
  - create
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apps"] # "" indicates the apps API group
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - watch
  - list
- apiGroups: ["batch"] # "" indicates the batch API group
  resources:
  - jobs
  - cronjobs
  verbs:
  - watch
  - list
# This is needed since OpenShift uses different KSM package which requires authentication
---
# Source: edgedelta-coordinator/templates/service_account.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgedelta-coordinator
  namespace: edgedelta
  labels:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
subjects:
- kind: ServiceAccount
  name: edgedelta-coordinator
  namespace: edgedelta
roleRef:
  kind: ClusterRole
  name: edgedelta-coordinator
  apiGroup: rbac.authorization.k8s.io
---
# Source: edgedelta-coordinator/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: edgedelta-coordinator-coordinator-svc
  namespace: edgedelta
  labels:
    version: v1
    kubernetes.io/cluster-service: "true"
    edgedelta/service-type: "coordinator"
spec:
  selector:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
    edgedelta/agent-type: processor
  ports:
    - port: 5555
      name: coordinator-port
---
# Source: edgedelta-coordinator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgedelta-coordinator
  namespace: edgedelta
  labels:
    app.kubernetes.io/name: edgedelta-coordinator
    app.kubernetes.io/instance: edgedelta-coordinator
    edgedelta/agent-type: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edgedelta-coordinator
      app.kubernetes.io/instance: edgedelta-coordinator
      edgedelta/agent-type: processor
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edgedelta-coordinator
        app.kubernetes.io/instance: edgedelta-coordinator
      
        edgedelta/agent-type: processor
    spec:
      serviceAccountName: edgedelta-coordinator
      containers:
        # agent container
        - name: edgedelta-coordinator-agent
          image: gcr.io/edgedelta/agent:v2.10.0
          ports:
            - name: coordinator
              containerPort: 5555
          env:
            - name: ED_FLEET_TYPE
              value: coordinator
            - name: ED_DISABLE_SAMPLE_COLLECTOR
              value: "1"
            - name: ED_COORDINATOR_SERVER_ENABLED
              value: "1"
            - name: ED_COORDINATOR_SERVER_PORT
              value: "5555"
            - name: ED_COORDINATOR_USE_BACKEND
              value: "1"
            - name: ED_DATA_PATH
              value: "/edgedelta/data"
            
            - name:  ED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: edgedelta-coordinator-api-key
                  key: ed-api-key
            - name: ED_ENABLE_PARENT_K8S_CONTROLLER_DISCOVERY
              value: "1"
            - name: ED_HOST_OVERRIDE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: ED_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: ED_K8S_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ED_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data-volume
              mountPath: /edgedelta/data
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: edgedelta-coordinator
