apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog-deployment
  labels:
    app: flog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flog
  template:
    metadata:
      labels:
        app: flog
    spec:
      containers:
      - name: flog
        image: docker.io/edgedelta/flog:latest
        args: ["-f", "apache_combined_simple", "-l", "-d", "0.1", "-e", "1500", "-c", "500"]
      # On older Kubernetes versions where OnFailure unsupported
      # restartPolicy: Always
      restartPolicy: OnFailure
