apiVersion: apps/v1
kind: Deployment
metadata:
  name: rehydration-handler
  namespace: edgedelta-rehydration
  labels:
    k8s-app: rehydration-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rehydration-handler
  template:
    metadata:
      labels:
        k8s-app: rehydration-handler
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: handler
        # image built on 2023-05-25 for on-prem release v0.1.55
        image: gcr.io/edgedelta/function:v0.1.55
        ports:
          - containerPort: 8080
        command:
          - /edgedelta/faas
        env:
          - name: ED_MODE
            value: "prod"
          - name: ED_REHYDRATION_PUSH_BATCH_SIZE
            value: "10000"
          - name: ED_HANDLER_NAME
            value: "rehydrate"
          - name: ED_REMOTE_REPOSITORY
            value: "1"
          - name: ED_REMOTE_TOKEN_FILE
            value: "/etc/ed-api-token/ed-api-token"
          # - name: ED_DISABLE_API_TLS_VERIFICATION
          #   value: "1"
          - name: GOGC
            value: "20"
          - name: GOMEMLIMIT
            value: 15GiB # This value should be less than memory limit of the pod, ideally 90% of the limit
          - name: GODEBUG
            value: madvdontneed=1
        resources:
          limits:
            cpu: 2000m
            memory: 16000Mi
          requests:
            cpu: 1000m
            memory: 16000Mi
        imagePullPolicy: Always
        volumeMounts:
        - name: ed-api-token
          mountPath: "/etc/ed-api-token"
          readOnly: true
      volumes:
      - name: ed-api-token
        secret:
          secretName: ed-api-token
---
apiVersion: v1
kind: Service
metadata:
  name: rehydration-handler
  namespace: edgedelta-rehydration
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    k8s-app: rehydration-handler